[package]
name = "lunatics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lunatic = { version = "0.14", features = ["msgpack_serializer"] }